### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by mikeerickson** [ttscoff/MarkedCustomStyles#24]
Hey Brett

I am trying to hunt down a good dark theme for Marked2, and am wondering if you have some suggestions.  I have scoured google, but hard to find something which has "preview" so I can actually see the in the wild.

If you have any suggestions, I would greatly appreciate.   In the meantime, I will continue to my search :-)

**Comment by ttscoff** [comment]
All of the built-in styles and many of the custom styles have a "High 
Contrast" mode, specified by the .inverted class. If you hit ⌘⌥I in 
Marked it will flip to the dark mode.

-Brett

**Comment by xguerin** [comment]
Sadly, the high contrast mode reverts the colors of dark syntax theme. Is there an alternative to the high contrast mode?
