### ISSUE TITLE
How do I style footer for paginated pdf? 

### ISSUE THREAD

**Issue by filipgoc** [ttscoff/MarkedCustomStyles#29]
Hi, 

What's the selector for the footer? I tried something like

```
#wrapper footer p {
color:#eb006a;
}
```

in the _additional CSS_, but to no avail. 

Since the footer only gets generated on export, I can't use the webkit inspector to figure this out, and I don't see footer styling in the example styles. 

Thanks!

**Comment by filipgoc** [comment]
Additionally, in the far future, it would be super useful to get pdf live preview as well! If I'm exporting to pdf, the html preview has limited usefulness...

**Comment by filipgoc** [comment]
PS: I see the styling is possible in the preferences, but I wonder if and how to include the style packaged to be shared with others.

**Comment by filipgoc** [comment]
Sorry about the many messages. I see you mentioned somewhere that pdf matter is styled elsewhere... but where.

**Comment by ttscoff** [comment]
Hi Filip,

The headers and footers are not generated via HTML, so there's no way to target styling on them through CSS. Only via the Export preferences. I don't currently offer a way to share those settings easily, but I've seen it required in a couple of instances now and I'm considering options there.

Live PDF preview is also something I've looked into. At the present time I'm working to improve RTF (and Word/Pages) export, after which I'll be working on a custom PDF renderer. Right now Marked 2 uses the macOS print system to generate the PDF from HTML, so a live preview would essentially be a constant print operation in the background. I think I have a plan for making something work once I have the custom engine worked out, but I don't have a timeline on that right now.

**Comment by ttscoff** [comment]
In regards to the [final message](https://github.com/ttscoff/MarkedCustomStyles/issues/29#issuecomment-404109786) above, I'm not sure what you mean. You can use @media specifiers in the CSS to control print/PDF-specific settings, if needed.

**Comment by filipgoc** [comment]
Thanks for all the information, that's what I needed!
